export interface Tool {
    id: string;
    name: string;
    description: string;
    category: string;
    subCategory?: string;
    slug: string;
    icon: string;
}

export const tools: Tool[] = [
    // ==========================================
    // 1. Finance / Money
    // ==========================================
    {
        id: 'emi-calculator',
        name: 'EMI',
        description: 'Calculate EMI.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage',
        slug: 'emi-calculator',
        icon: '🧮',
    },
    {
        id: 'loan-calculator',
        name: 'Loan',
        description: 'Loan repayment.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage',
        slug: 'loan-calculator',
        icon: '🏦',
    },
    {
        id: 'simple-interest-calculator',
        name: 'Simple Interest',
        description: 'Simple interest.',
        category: 'finance-money',
        subCategory: 'Interest',
        slug: 'simple-interest-calculator',
        icon: '➕',
    },
    {
        id: 'compound-interest-calculator',
        name: 'Compound Int.',
        description: 'Compound interest.',
        category: 'finance-money',
        subCategory: 'Interest',
        slug: 'compound-interest-calculator',
        icon: '🔄',
    },
    {
        id: 'sip-calculator',
        name: 'SIP',
        description: 'SIP returns.',
        category: 'finance-money',
        subCategory: 'Investment',
        slug: 'sip-calculator',
        icon: '🌱',
    },
    {
        id: 'fd-calculator',
        name: 'FD',
        description: 'Fixed Deposit.',
        category: 'finance-money',
        subCategory: 'Investment',
        slug: 'fd-calculator',
        icon: '💰',
    },
    {
        id: 'rd-calculator',
        name: 'RD',
        description: 'Recurring Deposit.',
        category: 'finance-money',
        subCategory: 'Investment',
        slug: 'rd-calculator',
        icon: '📉',
    },
    {
        id: 'mortgage-calculator',
        name: 'Mortgage',
        description: 'Monthly payments.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage',
        slug: 'mortgage-calculator',
        icon: '🏠',
    },
    {
        id: 'credit-card-payoff-calculator',
        name: 'CreditCard Payoff',
        description: 'Debt free plan.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage', // Mapping to loan for now
        slug: 'credit-card-payoff-calculator',
        icon: '💳',
    },
    {
        id: 'rent-vs-buy-calculator',
        name: 'Rent vs Buy',
        description: 'Rent or Buy decision.',
        category: 'finance-money',
        subCategory: 'Real Estate',
        slug: 'rent-vs-buy-calculator',
        icon: '🏠'
    },
    {
        id: 'auto-loan-calculator',
        name: 'Auto Loan',
        description: 'Car loan helper.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage',
        slug: 'auto-loan-calculator',
        icon: '🚗',
    },
    {
        id: 'amortization-calculator',
        name: 'Amortization',
        description: 'Loan schedule.',
        category: 'finance-money',
        subCategory: 'Loan & Mortgage',
        slug: 'amortization-calculator',
        icon: '📅',
    },

    {
        id: 'roi-calculator',
        name: 'ROI',
        description: 'Return on Inv.',
        category: 'finance-money',
        subCategory: 'Investment',
        slug: 'roi-calculator',
        icon: '📈',
    },
    {
        id: 'margin-calculator',
        name: 'Margin',
        description: 'Profit margin.',
        category: 'finance-money', // Moved from business-tools as per req (or math?) Finance fits.
        subCategory: 'Business',
        slug: 'margin-calculator',
        icon: '🏪',
    },
    {
        id: 'gdp-calculator',
        name: 'GDP',
        description: 'Economic output.',
        category: 'finance-money',
        subCategory: 'Economics',
        slug: 'gdp-calculator',
        icon: '🌍',
    },
    {
        id: 'inflation-calculator',
        name: 'Inflation',
        description: 'Money value.',
        category: 'finance-money',
        subCategory: 'Economics',
        slug: 'inflation-calculator',
        icon: '💸',
    },
    {
        id: 'salary-calculator',
        name: 'Salary',
        description: 'Hourly/Yearly.',
        category: 'finance-money', // Also listed in Utility, but Finance is primary
        subCategory: 'Income',
        slug: 'salary-calculator',
        icon: '💵',
    },
    {
        id: 'sales-tax-calculator',
        name: 'Sales Tax',
        description: 'Sales tax.',
        category: 'finance-money',
        subCategory: 'Tax',
        slug: 'sales-tax-calculator',
        icon: '🏷️',
    },
    {
        id: 'gst-calculator',
        name: 'GST',
        description: 'GST amount.',
        category: 'finance-money', // Also utility, but finance matches
        subCategory: 'Tax',
        slug: 'gst-calculator',
        icon: '📊',
    },
    {
        id: 'income-tax-calculator',
        name: 'Income Tax',
        description: 'Tax liability.',
        category: 'finance-money',
        subCategory: 'Tax',
        slug: 'income-tax-calculator',
        icon: '🧾',
    },
    {
        id: 'retirement-calculator',
        name: 'Retirement',
        description: 'Savings plan.',
        category: 'finance-money',
        subCategory: 'Retirement',
        slug: 'retirement-calculator',
        icon: '👴',
    },
    {
        id: '401k-calculator',
        name: '401k',
        description: '401k growth.',
        category: 'finance-money',
        subCategory: 'Retirement',
        slug: '401k-calculator',
        icon: '💼',
    },


    // ==========================================
    // 2. Percentage & Math
    // ==========================================
    {
        id: 'percentage-calculator',
        name: 'Percentage',
        description: 'Calculate %.',
        category: 'percentage-math',
        subCategory: 'Basic',
        slug: 'percentage-calculator',
        icon: '％',
    },
    {
        id: 'simple-calculator',
        name: 'Calculator',
        description: 'Basic math.',
        category: 'percentage-math',
        subCategory: 'Basic',
        slug: 'simple-calculator',
        icon: '🧮',
    },
    {
        id: 'scientific-calculator',
        name: 'Scientific',
        description: 'Advanced math.',
        category: 'percentage-math',
        subCategory: 'Basic',
        slug: 'scientific-calculator',
        icon: '🔬',
    },
    {
        id: 'fraction-calculator',
        name: 'Fraction',
        description: 'Fraction tool.',
        category: 'percentage-math',
        subCategory: 'Basic',
        slug: 'fraction-calculator',
        icon: '½',
    },
    {
        id: 'average-calculator',
        name: 'Average',
        description: 'Find average.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'average-calculator',
        icon: '📊',
    },
    {
        id: 'ratio-calculator',
        name: 'Ratio',
        description: 'Ratio solver.',
        category: 'percentage-math',
        subCategory: 'Algebra',
        slug: 'ratio-calculator',
        icon: '➗',
    },
    {
        id: 'lcm-calculator',
        name: 'LCM',
        description: 'Least common.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'lcm-calculator',
        icon: '🔢',
    },
    {
        id: 'gcf-calculator',
        name: 'HCF / GCF',
        description: 'Greatest common.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'gcf-calculator',
        icon: '🔢',
    },
    // Missing: Discount, Profit & Loss (Will add later)
    // Existing Math Tools
    {
        id: 'checkbook-balancer', // Renamed or kept? Assuming keep existing logic
        name: 'Checkbook',
        description: 'Balance checkbook.',
        category: 'finance-money', // Wait, this is finance
        subCategory: 'Personal Finance',
        slug: 'checkbook-balancer',
        icon: '📒',
    },
    {
        id: 'budget-calculator', // Duplicate ID above? No, checked tools.ts, id is budget-calculator.
        name: 'Budget',
        description: 'Monthly plan.',
        category: 'finance-money',
        subCategory: 'Personal Finance',
        slug: 'budget-calculator',
        icon: '📒',
    },
    {
        id: 'mean-median-mode-calculator',
        name: 'Mean Median',
        description: 'Averages.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'mean-median-mode-calculator',
        icon: '📊',
    },
    {
        id: 'standard-deviation-calculator',
        name: 'Deviation',
        description: 'SD & mean.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'standard-deviation-calculator',
        icon: '📊',
    },
    {
        id: 'triangle-calculator',
        name: 'Triangle',
        description: 'Angle & sides.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'triangle-calculator',
        icon: '📐',
    },
    {
        id: 'volume-calculator',
        name: 'Volume',
        description: 'Shape volume.',
        category: 'percentage-math', // Can also be in converters if unit conversion, but here is geometry
        subCategory: 'Geometry',
        slug: 'volume-calculator',
        icon: '🧊',
    },
    {
        id: 'area-calculator',
        name: 'Area',
        description: 'Shape area.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'area-calculator',
        icon: '⬛',
    },
    {
        id: 'surface-area-calculator',
        name: 'Surface Area',
        description: 'Surface area.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'surface-area-calculator',
        icon: '📦',
    },
    {
        id: 'circle-calculator',
        name: 'Circle',
        description: 'Circle props.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'circle-calculator',
        icon: '⭕',
    },
    {
        id: 'slope-calculator',
        name: 'Slope',
        description: 'Line slope.',
        category: 'percentage-math',
        subCategory: 'Algebra',
        slug: 'slope-calculator',
        icon: '📉',
    },
    {
        id: 'quadratic-formula-calculator',
        name: 'Quadratic',
        description: 'Quadratic eq.',
        category: 'percentage-math',
        subCategory: 'Algebra',
        slug: 'quadratic-formula-calculator',
        icon: '✖️',
    },
    {
        id: 'binary-calculator',
        name: 'Binary',
        description: 'Binary math.',
        category: 'percentage-math',
        subCategory: 'Algebra',
        slug: 'binary-calculator',
        icon: '0️⃣1️⃣',
    },
    {
        id: 'hex-calculator',
        name: 'Hex',
        description: 'Hex math.',
        category: 'percentage-math',
        subCategory: 'Algebra',
        slug: 'hex-calculator',
        icon: '🔠',
    },
    {
        id: 'prime-factorization-calculator',
        name: 'Prime Factors',
        description: 'Prime factors.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'prime-factorization-calculator',
        icon: '🔢',
    },
    {
        id: 'common-factor-calculator',
        name: 'Common Factor',
        description: 'Common factors.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'common-factor-calculator',
        icon: '🤝',
    },
    {
        id: 'factor-calculator',
        name: 'Factor',
        description: 'Find factors.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'factor-calculator',
        icon: '✖️',
    },
    {
        id: 'rounding-calculator',
        name: 'Rounding',
        description: 'Round numbers.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'rounding-calculator',
        icon: '🔄',
    },
    {
        id: 'root-calculator',
        name: 'Root',
        description: 'Square/Cube.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'root-calculator',
        icon: '🌳',
    },
    {
        id: 'exponent-calculator',
        name: 'Exponent',
        description: 'Power calc.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'exponent-calculator',
        icon: '📈',
    },
    {
        id: 'log-calculator',
        name: 'Log',
        description: 'Logarithms.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'log-calculator',
        icon: '🪵',
    },
    {
        id: 'permutation-combination-calculator',
        name: 'Permutations',
        description: 'Perm & Comb.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'permutation-combination-calculator',
        icon: '🔄',
    },
    {
        id: 'probability-calculator',
        name: 'Probability',
        description: 'Event prob.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'probability-calculator',
        icon: '🎲',
    },
    {
        id: 'statistics-calculator',
        name: 'Statistics',
        description: 'Basic stats.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'statistics-calculator',
        icon: '📉',
    },
    {
        id: 'z-score-calculator',
        name: 'Z-Score',
        description: 'Z-score.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'z-score-calculator',
        icon: '🇿',
    },
    {
        id: 'confidence-interval-calculator',
        name: 'Confidence',
        description: 'Intervals.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'confidence-interval-calculator',
        icon: '↔️',
    },
    {
        id: 'sample-size-calculator',
        name: 'Sample Size',
        description: 'Sample size.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'sample-size-calculator',
        icon: '👥',
    },
    {
        id: 'p-value-calculator',
        name: 'P-Value',
        description: 'Get P-value.',
        category: 'percentage-math',
        subCategory: 'Statistics',
        slug: 'p-value-calculator',
        icon: '🅿️',
    },
    {
        id: 'scientific-notation-calculator',
        name: 'Sci Notation',
        description: 'Sci notation.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'scientific-notation-calculator',
        icon: '🔬',
    },
    {
        id: 'big-number-calculator',
        name: 'Big Number',
        description: 'Large numbers.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'big-number-calculator',
        icon: '🐘',
    },
    {
        id: 'long-division-calculator',
        name: 'Long Division',
        description: 'Long division.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'long-division-calculator',
        icon: '➗',
    },
    {
        id: 'pythagorean-theorem-calculator',
        name: 'Pythagoras',
        description: 'Hypotenuse.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'pythagorean-theorem-calculator',
        icon: '📐',
    },
    {
        id: 'right-triangle-calculator',
        name: 'Right Tri',
        description: 'Right triangle.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'right-triangle-calculator',
        icon: '📐',
    },
    {
        id: 'random-number-generator',
        name: 'Random',
        description: 'RNG tool.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'random-number-generator',
        icon: '🎲',
    },
    {
        id: 'number-sequence-calculator',
        name: 'Sequence',
        description: 'Next number.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'number-sequence-calculator',
        icon: '🔢',
    },
    {
        id: 'percent-error-calculator',
        name: '% Error',
        description: '% Error.',
        category: 'percentage-math',
        subCategory: 'Numbers',
        slug: 'percent-error-calculator',
        icon: '❌',
    },
    {
        id: 'half-life-calculator',
        name: 'Half Life',
        description: 'Decay.',
        category: 'percentage-math', // Or science
        subCategory: 'Algebra',
        slug: 'half-life-calculator',
        icon: '☢️',
    },
    {
        id: 'matrix-calculator',
        name: 'Matrix',
        description: 'Matrix ops.',
        category: 'student-tools', // User put it in Percentage & Math implicitly? Actually User didn't specify, but I'll put it in Student as it was, or Math. Let's put in Math.
        subCategory: 'Algebra',
        slug: 'matrix-calculator',
        icon: '▦',
    },
    {
        id: 'distance-calculator',
        name: 'Distance',
        description: '2D Distance.',
        category: 'percentage-math',
        subCategory: 'Geometry',
        slug: 'distance-calculator',
        icon: '📏',
    },

    // ==========================================
    // 3. Health & Body
    // ==========================================
    {
        id: 'bmi-calculator',
        name: 'BMI',
        description: 'Body Mass Index.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'bmi-calculator',
        icon: '⚖️',
    },
    {
        id: 'bmr-calculator',
        name: 'BMR',
        description: 'Basic Metabolic.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'bmr-calculator',
        icon: '🔥',
    },
    {
        id: 'calorie-calculator',
        name: 'Calorie',
        description: 'Daily needs.',
        category: 'health-body',
        subCategory: 'Nutrition',
        slug: 'calorie-calculator',
        icon: '🍎',
    },
    {
        id: 'ideal-weight-calculator',
        name: 'Ideal Weight',
        description: 'Target weight.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'ideal-weight-calculator',
        icon: '🎯',
    },
    {
        id: 'body-fat-calculator',
        name: 'Body Fat',
        description: 'Fat percentage.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'body-fat-calculator',
        icon: '💪',
    },
    {
        id: 'due-date-calculator',
        name: 'Due Date',
        description: 'Baby due date.',
        category: 'health-body',
        subCategory: 'New Life', // Pregnancy
        slug: 'due-date-calculator',
        icon: '📅',
    },
    {
        id: 'ovulation-calculator',
        name: 'Ovulation',
        description: 'Fertile days.',
        category: 'health-body',
        subCategory: 'New Life',
        slug: 'ovulation-calculator',
        icon: '💐',
    },
    {
        id: 'pregnancy-calculator',
        name: 'Pregnancy',
        description: 'Weekly track.',
        category: 'health-body',
        subCategory: 'New Life',
        slug: 'pregnancy-calculator',
        icon: '🤰',
    },
    {
        id: 'pregnancy-weight-gain-calculator',
        name: 'Weight Gain',
        description: 'Pregnancy gain.',
        category: 'health-body',
        subCategory: 'New Life',
        slug: 'pregnancy-weight-gain-calculator',
        icon: '⚖️',
    },
    {
        id: 'pregnancy-conception-calculator',
        name: 'Conception',
        description: 'Conception date.',
        category: 'health-body',
        subCategory: 'New Life',
        slug: 'pregnancy-conception-calculator',
        icon: '👶',
    },
    {
        id: 'conception-calculator',
        name: 'Conception',
        description: 'Best dates.',
        category: 'health-body',
        subCategory: 'New Life',
        slug: 'conception-calculator',
        icon: '📅',
    },
    {
        id: 'period-calculator',
        name: 'Period',
        description: 'Cycle tracker.',
        category: 'health-body',
        subCategory: 'Women Health',
        slug: 'period-calculator',
        icon: '🩸',
    },
    {
        id: 'macro-calculator',
        name: 'Macro',
        description: 'Daily macros.',
        category: 'health-body',
        subCategory: 'Nutrition',
        slug: 'macro-calculator',
        icon: '🥩',
    },
    {
        id: 'protein-calculator',
        name: 'Protein',
        description: 'Protein needs.',
        category: 'health-body',
        subCategory: 'Nutrition',
        slug: 'protein-calculator',
        icon: '🍗',
    },
    {
        id: 'carbohydrate-calculator',
        name: 'Carbs',
        description: 'Carb needs.',
        category: 'health-body',
        subCategory: 'Nutrition',
        slug: 'carbohydrate-calculator',
        icon: '🍞',
    },
    {
        id: 'fat-intake-calculator',
        name: 'Fat Intake',
        description: 'Fat needs.',
        category: 'health-body',
        subCategory: 'Nutrition',
        slug: 'fat-intake-calculator',
        icon: '🥑',
    },
    {
        id: 'tdee-calculator',
        name: 'TDEE',
        description: 'Energy use.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'tdee-calculator',
        icon: '⚡',
    },
    {
        id: 'healthy-weight-calculator',
        name: 'Healthy Weight',
        description: 'Healthy range.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'healthy-weight-calculator',
        icon: '🍏',
    },
    {
        id: 'calories-burned-calculator',
        name: 'Calories Burned',
        description: 'Activity calories.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'calories-burned-calculator',
        icon: '🏃',
    },
    {
        id: 'pace-calculator',
        name: 'Pace',
        description: 'Running pace.',
        category: 'health-body',
        subCategory: 'Activity',
        slug: 'pace-calculator',
        icon: '⏱️',
    },
    {
        id: 'target-heart-rate-calculator',
        name: 'Heart Rate',
        description: 'Target zone.',
        category: 'health-body',
        subCategory: 'Activity',
        slug: 'target-heart-rate-calculator',
        icon: '❤️',
    },
    {
        id: 'one-rep-max-calculator',
        name: '1 Rep Max',
        description: 'Max lift.',
        category: 'health-body',
        subCategory: 'Activity',
        slug: 'one-rep-max-calculator',
        icon: '🏋️‍♀️',
    },
    {
        id: 'lean-body-mass-calculator',
        name: 'Lean Mass',
        description: 'Muscle mass.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'lean-body-mass-calculator',
        icon: '🏋️',
    },
    {
        id: 'army-body-fat-calculator',
        name: 'Army Fat',
        description: 'Army Std Fat.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'army-body-fat-calculator',
        icon: '🎖️',
    },
    {
        id: 'gfr-calculator',
        name: 'GFR',
        description: 'Kidney func.',
        category: 'health-body',
        subCategory: 'Medical',
        slug: 'gfr-calculator',
        icon: '🩺',
    },
    {
        id: 'body-type-calculator',
        name: 'Body Type',
        description: 'Shape.',
        category: 'health-body',
        subCategory: 'Body',
        slug: 'body-type-calculator',
        icon: '👤',
    },
    {
        id: 'body-surface-area-calculator',
        name: 'BSA',
        description: 'Surface Area.',
        category: 'health-body',
        subCategory: 'Medical',
        slug: 'body-surface-area-calculator',
        icon: '📏',
    },
    {
        id: 'bac-calculator',
        name: 'BAC',
        description: 'Alcohol content.',
        category: 'health-body',
        subCategory: 'Medical',
        slug: 'bac-calculator',
        icon: '🍷',
    },
    {
        id: 'anorexic-bmi-calculator',
        name: 'Anorexic BMI',
        description: 'Underweight.',
        category: 'health-body',
        subCategory: 'Medical',
        slug: 'anorexic-bmi-calculator',
        icon: '⚠️',
    },
    {
        id: 'overweight-calculator',
        name: 'Overweight',
        description: 'Risk check.',
        category: 'health-body',
        subCategory: 'Medical',
        slug: 'overweight-calculator',
        icon: '⚖️',
    },
    {
        id: 'weight-watchers-points-calculator',
        name: 'WW Points',
        description: 'Diet points.',
        category: 'health-body',
        subCategory: 'Diet',
        slug: 'weight-watchers-points-calculator',
        icon: 'points',
    },


    {
        id: 'weight-loss-calculator',
        name: 'Weight Loss',
        description: 'Planner.',
        category: 'health-body',
        subCategory: 'Weight & Fitness',
        slug: 'weight-loss-calculator',
        icon: '📉',
    },

    // ==========================================
    // 4. Time & Date
    // ==========================================
    {
        id: 'age-calculator',
        name: 'Age',
        description: 'Calculate age.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'age-calculator',
        icon: '🎂',
    },
    {
        id: 'date-calculator',
        name: 'Date Difference',
        description: 'Compare dates.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'date-calculator',
        icon: '📅',
    },
    {
        id: 'time-calculator',
        name: 'Time',
        description: 'Add/Sub time.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'time-calculator',
        icon: '⏰',
    },
    {
        id: 'time-duration-calculator',
        name: 'Duration',
        description: 'Time span.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'time-duration-calculator',
        icon: '⏱️',
    },
    {
        id: 'day-of-the-week-calculator',
        name: 'Weekday',
        description: 'Find day.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'day-of-the-week-calculator',
        icon: '📅',
    },
    {
        id: 'day-counter',
        name: 'Day Counter',
        description: 'Count days.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'day-counter',
        icon: '📆',
    },
    {
        id: 'work-hours-calculator',
        name: 'Work Hours',
        description: 'Work time.',
        category: 'time-date',
        subCategory: 'Productivity',
        slug: 'hours-calculator',
        icon: '⏳',
    },
    {
        id: 'time-card-calculator',
        name: 'Time Card',
        description: 'Weekly hours.',
        category: 'time-date',
        subCategory: 'Productivity',
        slug: 'time-card-calculator',
        icon: '📋',
    },
    {
        id: 'time-zone-calculator',
        name: 'Time Zone',
        description: 'World clock.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'time-zone-calculator',
        icon: '🌍',
    },
    {
        id: 'countdown-timer',
        name: 'Countdown',
        description: 'Timer.',
        category: 'time-date',
        subCategory: 'General',
        slug: 'countdown-timer',
        icon: '⏳',
    },
    {
        id: 'working-days-calculator',
        name: 'Working Days',
        description: 'Business days.',
        category: 'time-date',
        subCategory: 'Productivity',
        slug: 'working-days-calculator',
        icon: '📅',
    },

    // ==========================================
    // 5. Unit Converters
    // ==========================================
    {
        id: 'currency-converter',
        name: 'Currency',
        description: 'Exchange rates.',
        category: 'unit-converters',
        subCategory: 'Money',
        slug: 'currency-converter',
        icon: '💱',
    },
    {
        id: 'conversion-calculator',
        name: 'Unit Converter',
        description: 'All units.',
        category: 'unit-converters',
        subCategory: 'General',
        slug: 'conversion-calculator',
        icon: '🔄',
    },
    {
        id: 'weight-calculator',
        name: 'Weight',
        description: 'Kg to Lb etc.',
        category: 'unit-converters',
        subCategory: 'Mass',
        slug: 'weight-calculator',
        icon: '🏋️',
    },
    {
        id: 'speed-calculator', // Can be physics or converter
        name: 'Speed',
        description: 'Speed units.',
        category: 'unit-converters',
        subCategory: 'Physics',
        slug: 'speed-calculator',
        icon: '🏎️',
    },
    {
        id: 'shoe-size-conversion',
        name: 'Shoe Size',
        description: 'Intl sizes.',
        category: 'unit-converters',
        subCategory: 'Clothing',
        slug: 'shoe-size-conversion',
        icon: '👟',
    },
    {
        id: 'roman-numeral-converter',
        name: 'Roman Numerals',
        description: 'I, V, X...',
        category: 'unit-converters',
        subCategory: 'Numbers',
        slug: 'roman-numeral-converter',
        icon: '🏛️',
    },
    {
        id: 'length-converter',
        name: 'Length',
        description: 'M, Km, Ft...',
        category: 'unit-converters',
        subCategory: 'Physics',
        slug: 'length-converter',
        icon: '📏',
    },
    {
        id: 'temperature-converter',
        name: 'Temperature',
        description: 'C, F, K.',
        category: 'unit-converters',
        subCategory: 'Physics',
        slug: 'temperature-converter',
        icon: '🌡️',
    },
    {
        id: 'area-converter',
        name: 'Area',
        description: 'Sq meters...',
        category: 'unit-converters',
        subCategory: 'Geometry',
        slug: 'area-converter',
        icon: '⬛',
    },
    {
        id: 'volume-converter',
        name: 'Volume',
        description: 'Liters, Gal...',
        category: 'unit-converters',
        subCategory: 'Geometry',
        slug: 'volume-converter',
        icon: '🧊',
    },
    {
        id: 'time-converter',
        name: 'Time Units',
        description: 'Sec, Min, Hr...',
        category: 'unit-converters',
        subCategory: 'Physics',
        slug: 'time-converter',
        icon: '⏱️',
    },

    // ==========================================
    // 6. Student / Exam
    // ==========================================
    {
        id: 'gpa-calculator',
        name: 'GPA',
        description: 'Grade Point Avg.',
        category: 'student-exam',
        subCategory: 'Grades',
        slug: 'gpa-calculator',
        icon: '🎓',
    },
    {
        id: 'grade-calculator',
        name: 'Grade Info',
        description: 'Final grade.',
        category: 'student-exam',
        subCategory: 'Grades',
        slug: 'grade-calculator',
        icon: '📝',
    },
    {
        id: 'cgpa-calculator',
        name: 'CGPA',
        description: 'Cumulative GPA.',
        category: 'student-exam',
        subCategory: 'Grades',
        slug: 'cgpa-calculator',
        icon: '🎓',
    },
    {
        id: 'percentage-to-cgpa-calculator',
        name: '% to CGPA',
        description: 'Convert score.',
        category: 'student-exam',
        subCategory: 'Grades',
        slug: 'percentage-to-cgpa-calculator',
        icon: '🔄',
    },
    {
        id: 'marks-percentage-calculator',
        name: 'Marks %',
        description: 'Exam score.',
        category: 'student-exam',
        subCategory: 'Grades',
        slug: 'marks-percentage-calculator',
        icon: '💯',
    },
    {
        id: 'attendance-calculator',
        name: 'Attendance',
        description: 'Track attendance.',
        category: 'student-exam',
        subCategory: 'Study',
        slug: 'attendance-calculator',
        icon: '🙋',
    },
    // Included AI Student Tools here
    {
        id: 'ai-essay-writer',
        name: 'Essay Writer',
        description: 'AI Writer.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'ai-essay-writer',
        icon: '✍️',
    },
    {
        id: 'ai-paragraph-rewriter',
        name: 'Rewriter',
        description: 'Fix flow.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'ai-paragraph-rewriter',
        icon: '🔄',
    },
    {
        id: 'ai-summary-generator',
        name: 'Summarizer',
        description: 'Summarize text.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'ai-summary-generator',
        icon: '📝',
    },
    {
        id: 'ai-citation-generator',
        name: 'Citation',
        description: 'APA/MLA.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'ai-citation-generator',
        icon: '📖',
    },
    {
        id: 'plagiarism-checker',
        name: 'Plagiarism',
        description: 'Check copy.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'plagiarism-checker',
        icon: '🕵️',
    },
    {
        id: 'ai-flashcard-generator',
        name: 'Flashcards',
        description: 'Study aid.',
        category: 'student-exam',
        subCategory: 'Study',
        slug: 'ai-flashcard-generator',
        icon: '📇',
    },
    {
        id: 'grammar-checker',
        name: 'Grammar',
        description: 'Fix errors.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'grammar-checker',
        icon: '✔️',
    },
    {
        id: 'sentence-rewriter',
        name: 'Rephrase',
        description: 'Better sentences.',
        category: 'student-exam',
        subCategory: 'Writing',
        slug: 'sentence-rewriter',
        icon: '🗣️',
    },
    {
        id: 'translation-tool',
        name: 'Translator',
        description: 'Language map.',
        category: 'student-exam',
        subCategory: 'Languages',
        slug: 'translation-tool',
        icon: '🌐',
    },
    {
        id: 'reading-time-calculator',
        name: 'Read Time',
        description: 'Est time.',
        category: 'student-exam',
        subCategory: 'Reading',
        slug: 'reading-time-calculator',
        icon: '⏱️',
    },
    // Study File Tools
    {
        id: 'handwriting-to-text',
        name: 'Handwriting OCR',
        description: 'Digitize notes.',
        category: 'student-exam',
        subCategory: 'Files',
        slug: 'handwriting-to-text',
        icon: '🖊️',
    },
    {
        id: 'screenshot-to-pdf',
        name: 'Screen to PDF',
        description: 'Save lecture.',
        category: 'student-exam',
        subCategory: 'Files',
        slug: 'screenshot-to-pdf',
        icon: '📸',
    },
    {
        id: 'video-to-text',
        name: 'Video Notes',
        description: 'Transcribe vid.',
        category: 'student-exam',
        subCategory: 'Files',
        slug: 'video-to-text',
        icon: '📹',
    },
    {
        id: 'audio-to-text',
        name: 'Audio Notes',
        description: 'Transcribe audio.',
        category: 'student-exam',
        subCategory: 'Files',
        slug: 'audio-to-text',
        icon: '🎙️',
    },
    // Advanced math for students
    {
        id: 'derivative-calculator',
        name: 'Derivative',
        description: 'Calculus.',
        category: 'student-exam',
        subCategory: 'Math',
        slug: 'derivative-calculator',
        icon: '∂',
    },
    {
        id: 'integral-calculator',
        name: 'Integral',
        description: 'Calculus.',
        category: 'student-exam',
        subCategory: 'Math',
        slug: 'integral-calculator',
        icon: '∫',
    },
    {
        id: 'equation-solver',
        name: 'Equation Solver',
        description: 'Find X.',
        category: 'student-exam',
        subCategory: 'Math',
        slug: 'equation-solver',
        icon: 'x=',
    },

    // ==========================================
    // 7. Utility
    // ==========================================
    {
        id: 'fuel-cost-calculator',
        name: 'Fuel Cost',
        description: 'Trip cost.',
        category: 'utility',
        subCategory: 'Travel',
        slug: 'fuel-cost-calculator',
        icon: '⛽',
    },
    {
        id: 'electricity-calculator',
        name: 'Electricity Bill',
        description: 'Usage cost.',
        category: 'utility',
        subCategory: 'Home',
        slug: 'electricity-calculator',
        icon: '💡',
    },
    {
        id: 'tip-calculator',
        name: 'Tip',
        description: 'Gratuity.',
        category: 'utility',
        subCategory: 'Everyday',
        slug: 'tip-calculator',
        icon: '💵',
    },
    {
        id: 'password-generator',
        name: 'Password Gen',
        description: 'Secure pass.',
        category: 'utility',
        subCategory: 'Tech',
        slug: 'password-generator',
        icon: '🔒',
    },
    {
        id: 'dice-roller',
        name: 'Dice Roller',
        description: 'Random.',
        category: 'utility',
        subCategory: 'Games',
        slug: 'dice-roller',
        icon: '🎲',
    },
    {
        id: 'mileage-calculator',
        name: 'Mileage',
        description: 'Vehicle stats.',
        category: 'utility',
        subCategory: 'Travel',
        slug: 'mileage-calculator',
        icon: '🛣️',
    },
    {
        id: 'gas-mileage-calculator',
        name: 'MPG',
        description: 'Fuel eff.',
        category: 'utility',
        subCategory: 'Travel',
        slug: 'gas-mileage-calculator',
        icon: '🚗',
    },
    {
        id: 'love-calculator',
        name: 'Love Calc',
        description: 'Fun.',
        category: 'utility',
        subCategory: 'Fun',
        slug: 'love-calculator',
        icon: '💘',
    },
    {
        id: 'height-calculator',
        name: 'Child Height',
        description: 'Predict.',
        category: 'utility',
        subCategory: 'Family',
        slug: 'height-calculator',
        icon: '📏',
    },
    {
        id: 'sleep-calculator',
        name: 'Sleep Cycle',
        description: 'Wake time.',
        category: 'utility',
        subCategory: 'Health',
        slug: 'sleep-calculator',
        icon: '😴',
    },
    {
        id: 'btu-calculator',
        name: 'AC BTU',
        description: 'AC Size.',
        category: 'utility',
        subCategory: 'Home',
        slug: 'btu-calculator',
        icon: '❄️',
    },
    {
        id: 'square-footage-calculator',
        name: 'Square Footage',
        description: 'Area.',
        category: 'utility',
        subCategory: 'Home',
        slug: 'square-footage-calculator',
        icon: '⬛',
    },
    {
        id: 'voltage-drop-calculator',
        name: 'Voltage Drop',
        description: 'Electric.',
        category: 'utility',
        subCategory: 'Engineering',
        slug: 'voltage-drop-calculator',
        icon: '⚡',
    },
    {
        id: 'resistor-calculator',
        name: 'Resistor',
        description: 'Ohms.',
        category: 'utility',
        subCategory: 'Engineering',
        slug: 'resistor-calculator',
        icon: '🔌',
    },
    {
        id: 'ohms-law-calculator',
        name: 'Ohms Law',
        description: 'V=IR',
        category: 'utility',
        subCategory: 'Engineering',
        slug: 'ohms-law-calculator',
        icon: '🔋',
    },
    {
        id: 'horsepower-calculator',
        name: 'Horsepower',
        description: 'Power.',
        category: 'utility',
        subCategory: 'Auto',
        slug: 'horsepower-calculator',
        icon: '🐎',
    },
    {
        id: 'engine-horsepower-calculator',
        name: 'Engine HP',
        description: 'Engine.',
        category: 'utility',
        subCategory: 'Auto',
        slug: 'engine-horsepower-calculator',
        icon: '⚙️',
    },
    {
        id: 'tire-size-calculator',
        name: 'Tire Size',
        description: 'Comparison.',
        category: 'utility',
        subCategory: 'Auto',
        slug: 'tire-size-calculator',
        icon: '🛞',
    },
    {
        id: 'molecular-weight-calculator',
        name: 'Mol Weight',
        description: 'Chemistry.',
        category: 'utility',
        subCategory: 'Science',
        slug: 'molecular-weight-calculator',
        icon: '⚛️',
    },
    {
        id: 'molarity-calculator',
        name: 'Molarity',
        description: 'Chem Conc.',
        category: 'utility',
        subCategory: 'Science',
        slug: 'molarity-calculator',
        icon: '🧪',
    },
    {
        id: 'density-calculator',
        name: 'Density',
        description: 'Phys prop.',
        category: 'utility',
        subCategory: 'Science',
        slug: 'density-calculator',
        icon: '🧱',
    },
    {
        id: 'mass-calculator',
        name: 'Mass',
        description: 'Weight.',
        category: 'utility',
        subCategory: 'Science',
        slug: 'mass-calculator',
        icon: '⚖️',
    },

    // Construction (Grouping under Utility or separate? User didn't specify. Put in Utility -> Construction)
    {
        id: 'concrete-calculator',
        name: 'Concrete',
        description: 'Mix.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'concrete-calculator',
        icon: '🧱',
    },
    {
        id: 'roofing-calculator',
        name: 'Roofing',
        description: 'Shingles.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'roofing-calculator',
        icon: '🏠',
    },
    {
        id: 'tile-calculator',
        name: 'Tile',
        description: 'Flooring.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'tile-calculator',
        icon: '⬜',
    },
    {
        id: 'stair-calculator',
        name: 'Stairs',
        description: 'Rise run.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'stair-calculator',
        icon: '🪜',
    },
    {
        id: 'mulch-calculator',
        name: 'Mulch',
        description: 'Garden.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'mulch-calculator',
        icon: '🍂',
    },
    {
        id: 'gravel-calculator',
        name: 'Gravel',
        description: 'Driveway.',
        category: 'utility',
        subCategory: 'Construction',
        slug: 'gravel-calculator',
        icon: '🪨',
    },

    // Tech Utility
    {
        id: 'ip-subnet-calculator',
        name: 'Subnet',
        description: 'Network.',
        category: 'utility',
        subCategory: 'Tech',
        slug: 'ip-subnet-calculator',
        icon: '🌐',
    },
    {
        id: 'bandwidth-calculator',
        name: 'Bandwidth',
        description: 'Data rate.',
        category: 'utility',
        subCategory: 'Tech',
        slug: 'bandwidth-calculator',
        icon: '📶',
    },

    // Weather (Utility)
    {
        id: 'wind-chill-calculator',
        name: 'Wind Chill',
        description: 'Feels like.',
        category: 'utility',
        subCategory: 'Weather',
        slug: 'wind-chill-calculator',
        icon: '🌬️',
    },
    {
        id: 'heat-index-calculator',
        name: 'Heat Index',
        description: 'Humidity.',
        category: 'utility',
        subCategory: 'Weather',
        slug: 'heat-index-calculator',
        icon: '🌡️',
    },
    {
        id: 'dew-point-calculator',
        name: 'Dew Point',
        description: 'Moisture.',
        category: 'utility',
        subCategory: 'Weather',
        slug: 'dew-point-calculator',
        icon: '💧',
    },

    // ==========================================
    // Legacy / Specialized Categories (Preserved)
    // ==========================================
    // PDF Tools
    {
        id: 'merge-pdf',
        name: 'Merge',
        description: 'Combine PDFs.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'merge-pdf',
        icon: '📄',
    },
    {
        id: 'split-pdf',
        name: 'Split',
        description: 'Split PDF.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'split-pdf',
        icon: '✂️',
    },
    {
        id: 'remove-pages',
        name: 'Remove Pages',
        description: 'Delete.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'remove-pages',
        icon: '❌',
    },
    {
        id: 'extract-pages',
        name: 'Extract',
        description: 'Get pages.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'extract-pages',
        icon: '📤',
    },
    {
        id: 'organize-pdf',
        name: 'Organize',
        description: 'Sort.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'organize-pdf',
        icon: '📑',
    },
    {
        id: 'scan-to-pdf',
        name: 'Scan',
        description: 'Image to PDF.',
        category: 'pdf-tools',
        subCategory: 'Organize',
        slug: 'scan-to-pdf',
        icon: '📷',
    },
    {
        id: 'compress-pdf',
        name: 'Compress',
        description: 'Shrink.',
        category: 'pdf-tools',
        subCategory: 'Optimize',
        slug: 'compress-pdf',
        icon: '📉',
    },
    {
        id: 'repair-pdf',
        name: 'Repair',
        description: 'Fix.',
        category: 'pdf-tools',
        subCategory: 'Optimize',
        slug: 'repair-pdf',
        icon: '🔧',
    },
    {
        id: 'ocr-pdf',
        name: 'OCR',
        description: 'Searchable.',
        category: 'pdf-tools',
        subCategory: 'Optimize',
        slug: 'ocr-pdf',
        icon: '🔍',
    },
    {
        id: 'jpg-to-pdf',
        name: 'JPG to PDF',
        description: 'Convert.',
        category: 'pdf-tools',
        subCategory: 'Convert To',
        slug: 'jpg-to-pdf',
        icon: '🖼️',
    },
    {
        id: 'word-to-pdf',
        name: 'Word to PDF',
        description: 'Convert.',
        category: 'pdf-tools',
        subCategory: 'Convert To',
        slug: 'word-to-pdf',
        icon: '📝',
    },
    {
        id: 'powerpoint-to-pdf',
        name: 'PPT to PDF',
        description: 'Convert.',
        category: 'pdf-tools',
        subCategory: 'Convert To',
        slug: 'powerpoint-to-pdf',
        icon: '📊',
    },
    {
        id: 'excel-to-pdf',
        name: 'Excel to PDF',
        description: 'Convert.',
        category: 'pdf-tools',
        subCategory: 'Convert To',
        slug: 'excel-to-pdf',
        icon: '📈',
    },
    {
        id: 'html-to-pdf',
        name: 'Web to PDF',
        description: 'Convert.',
        category: 'pdf-tools',
        subCategory: 'Convert To',
        slug: 'html-to-pdf',
        icon: '🌐',
    },
    {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        description: 'Image.',
        category: 'pdf-tools',
        subCategory: 'Convert From',
        slug: 'pdf-to-jpg',
        icon: '🖼️',
    },
    {
        id: 'pdf-to-word',
        name: 'PDF to Word',
        description: 'Doc.',
        category: 'pdf-tools',
        subCategory: 'Convert From',
        slug: 'pdf-to-word',
        icon: '📝',
    },
    {
        id: 'pdf-to-powerpoint',
        name: 'PDF to PPT',
        description: 'Slides.',
        category: 'pdf-tools',
        subCategory: 'Convert From',
        slug: 'pdf-to-powerpoint',
        icon: '📊',
    },
    {
        id: 'pdf-to-excel',
        name: 'PDF to Excel',
        description: 'Sheet.',
        category: 'pdf-tools',
        subCategory: 'Convert From',
        slug: 'pdf-to-excel',
        icon: '📈',
    },
    {
        id: 'pdf-to-pdf-a',
        name: 'Archive',
        description: 'PDF/A.',
        category: 'pdf-tools',
        subCategory: 'Convert From',
        slug: 'pdf-to-pdf-a',
        icon: '🗄️',
    },
    {
        id: 'rotate-pdf',
        name: 'Rotate',
        description: 'Turn pages.',
        category: 'pdf-tools',
        subCategory: 'Edit',
        slug: 'rotate-pdf',
        icon: '🔄',
    },
    {
        id: 'add-page-numbers',
        name: 'Pg Numbers',
        description: 'Paginate.',
        category: 'pdf-tools',
        subCategory: 'Edit',
        slug: 'add-page-numbers',
        icon: '🔢',
    },
    {
        id: 'add-watermark',
        name: 'Watermark',
        description: 'Stamp.',
        category: 'pdf-tools',
        subCategory: 'Edit',
        slug: 'add-watermark',
        icon: '💧',
    },
    {
        id: 'crop-pdf',
        name: 'Crop',
        description: 'Trim.',
        category: 'pdf-tools',
        subCategory: 'Edit',
        slug: 'crop-pdf',
        icon: '✂️',
    },
    {
        id: 'edit-pdf',
        name: 'Edit PDF',
        description: 'Modify.',
        category: 'pdf-tools',
        subCategory: 'Edit',
        slug: 'edit-pdf',
        icon: '✏️',
    },
    {
        id: 'unlock-pdf',
        name: 'Unlock',
        description: 'Remove PW.',
        category: 'pdf-tools',
        subCategory: 'Security',
        slug: 'unlock-pdf',
        icon: '🔓',
    },
    {
        id: 'protect-pdf',
        name: 'Protect',
        description: 'Add PW.',
        category: 'pdf-tools',
        subCategory: 'Security',
        slug: 'protect-pdf',
        icon: '🛡️',
    },
    {
        id: 'sign-pdf',
        name: 'Sign',
        description: 'Signature.',
        category: 'pdf-tools',
        subCategory: 'Security',
        slug: 'sign-pdf',
        icon: '✒️',
    },
    {
        id: 'redact-pdf',
        name: 'Redact',
        description: 'Sanitize.',
        category: 'pdf-tools',
        subCategory: 'Security',
        slug: 'redact-pdf',
        icon: '⬛',
    },
    {
        id: 'compare-pdf',
        name: 'Compare',
        description: 'Diff.',
        category: 'pdf-tools',
        subCategory: 'Security',
        slug: 'compare-pdf',
        icon: '⚖️',
    },

    // Image Tools (Keep as is)
    {
        id: 'jpg-to-png',
        name: 'JpgToPng',
        description: 'Convert.',
        category: 'image-tools',
        subCategory: 'Convert',
        slug: 'jpg-to-png',
        icon: '🖼️',
    },
    {
        id: 'png-to-jpg',
        name: 'PngToJpg',
        description: 'Convert.',
        category: 'image-tools',
        subCategory: 'Convert',
        slug: 'png-to-jpg',
        icon: '🔄',
    },
    {
        id: 'image-to-base64',
        name: 'ImgToBase64',
        description: 'Encode.',
        category: 'image-tools',
        subCategory: 'Convert',
        slug: 'image-to-base64',
        icon: '💻',
    },
    {
        id: 'base64-to-image',
        name: 'Base64ToImg',
        description: 'Decode.',
        category: 'image-tools',
        subCategory: 'Convert',
        slug: 'base64-to-image',
        icon: '🖼️',
    },
    {
        id: 'image-resizer',
        name: 'Resize',
        description: 'Scale.',
        category: 'image-tools',
        subCategory: 'Edit',
        slug: 'image-resizer',
        icon: '📐',
    },
    {
        id: 'image-compressor',
        name: 'Compress',
        description: 'Shrink.',
        category: 'image-tools',
        subCategory: 'Edit',
        slug: 'image-compressor',
        icon: '📉',
    },
    {
        id: 'bg-remove',
        name: 'Bg Remover',
        description: 'AI Remove.',
        category: 'image-tools',
        subCategory: 'AI',
        slug: 'bg-remove',
        icon: '🎭',
    },
    // Truncating some image tools for brevity in this list, assuming standard ones exist
    {
        id: 'color-picker',
        name: 'Color Picker',
        description: 'Code.',
        category: 'image-tools',
        subCategory: 'Util',
        slug: 'color-picker',
        icon: '🎨',
    },

    // Business Tools (Preserved non-finance marketing/legal ones)
    {
        id: 'privacy-policy-generator',
        name: 'Privacy Policy',
        description: 'Legal.',
        category: 'business-tools',
        subCategory: 'Legal',
        slug: 'privacy-policy-generator',
        icon: '⚖️',
    },
    {
        id: 'terms-generator',
        name: 'Terms & Cond',
        description: 'Legal.',
        category: 'business-tools',
        subCategory: 'Legal',
        slug: 'terms-generator',
        icon: '📜',
    },
    {
        id: 'qr-code-generator',
        name: 'QR Code',
        description: 'Generate.',
        category: 'business-tools',
        subCategory: 'Marketing',
        slug: 'qr-code-generator',
        icon: '📱',
    },
    {
        id: 'invoice-generator',
        name: 'Invoice',
        description: 'Bill.',
        category: 'business-tools',
        subCategory: 'Finance',
        slug: 'invoice-generator',
        icon: '🧾',
    },
    {
        id: 'cpm-calculator',
        name: 'CPM',
        description: 'Ads.',
        category: 'business-tools',
        subCategory: 'Marketing',
        slug: 'cpm-calculator',
        icon: '📢',
    },
    {
        id: 'barcode-generator',
        name: 'Barcode',
        description: 'Gen.',
        category: 'business-tools',
        subCategory: 'Marketing',
        slug: 'barcode-generator',
        icon: '║▌',
    },
    {
        id: 'startup-name-generator',
        name: 'Name Gen',
        description: 'ldeas.',
        category: 'business-tools',
        subCategory: 'Marketing',
        slug: 'startup-name-generator',
        icon: '💡',
    },

    // Text Tools (Preserved)
    {
        id: 'word-counter',
        name: 'Word Count',
        description: 'Stats.',
        category: 'text-tools',
        subCategory: 'Analysis',
        slug: 'word-counter',
        icon: '📝',
    },
    {
        id: 'case-converter',
        name: 'Case Convert',
        description: 'Upper/Lower.',
        category: 'text-tools',
        subCategory: 'Edit',
        slug: 'case-converter',
        icon: '🔠',
    },
    {
        id: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum',
        description: 'Dummy text.',
        category: 'text-tools',
        subCategory: 'Gen',
        slug: 'lorem-ipsum-generator',
        icon: '📄',
    },
];

export const STUDENT_FAVORITE_IDS = [
    'scientific-calculator', 'gpa-calculator', 'percentage-calculator', 'simple-calculator',
    'fraction-calculator', 'ai-essay-writer', 'plagiarism-checker', 'grammar-checker'
];

export const categories = [
    { id: 'finance-money', name: 'Finance / Money', icon: '🏦' },
    { id: 'percentage-math', name: 'Percentage & Math', icon: '🔢' },
    { id: 'health-body', name: 'Health & Body', icon: '🏃' },
    { id: 'unit-converters', name: 'Unit Converters', icon: '📏' },
    { id: 'time-date', name: 'Time & Date', icon: '⏰' },
    { id: 'student-exam', name: 'Student / Exam', icon: '📚' },
    { id: 'utility', name: 'Utility', icon: '🌍' },
    // Ancillary categories
    { id: 'pdf-tools', name: 'PDF Tools', icon: '📄' },
    { id: 'image-tools', name: 'Image Tools', icon: '🖼️' },
    { id: 'text-tools', name: 'Text Tools', icon: '📝' },
    { id: 'business-tools', name: 'Business Tools', icon: '💼' },
];
