export interface Tool {
    id: string;
    name: string;
    description: string;
    category: string;
    subCategory?: string; // Added for grouping within a category
    slug: string;
    icon: string;
}

export const tools: Tool[] = [
    // --- PDF Tools ---
    // 1. ORGANIZE PDF
    {
        id: 'merge-pdf',
        name: 'Merge PDF',
        description: 'Combine multiple PDFs into one single PDF file.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'merge-pdf',
        icon: '📄',
    },
    {
        id: 'split-pdf',
        name: 'Split PDF',
        description: 'Split a PDF into multiple files.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'split-pdf',
        icon: '✂️',
    },
    {
        id: 'remove-pages',
        name: 'Remove Pages',
        description: 'Remove specific pages from a PDF file.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'remove-pages',
        icon: '❌',
    },
    {
        id: 'extract-pages',
        name: 'Extract Pages',
        description: 'Extract specific pages from a PDF.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'extract-pages',
        icon: '📤',
    },
    {
        id: 'organize-pdf',
        name: 'Organize PDF',
        description: 'Sort pages of your PDF file.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'organize-pdf',
        icon: '📑',
    },
    {
        id: 'scan-to-pdf',
        name: 'Scan to PDF',
        description: 'Convert scanned images to PDF.',
        category: 'pdf-tools',
        subCategory: 'Organize PDF',
        slug: 'scan-to-pdf',
        icon: '📷',
    },

    // 2. OPTIMIZE PDF
    {
        id: 'compress-pdf',
        name: 'Compress PDF',
        description: 'Reduce PDF file size while maintaining quality.',
        category: 'pdf-tools',
        subCategory: 'Optimize PDF',
        slug: 'compress-pdf',
        icon: '📉',
    },
    {
        id: 'repair-pdf',
        name: 'Repair PDF',
        description: 'Recover data from a corrupted PDF file.',
        category: 'pdf-tools',
        subCategory: 'Optimize PDF',
        slug: 'repair-pdf',
        icon: '🔧',
    },
    {
        id: 'ocr-pdf',
        name: 'OCR PDF',
        description: 'Convert scanned PDF to searchable text.',
        category: 'pdf-tools',
        subCategory: 'Optimize PDF',
        slug: 'ocr-pdf',
        icon: '🔍',
    },

    // 3. CONVERT TO PDF
    {
        id: 'jpg-to-pdf',
        name: 'JPG to PDF',
        description: 'Convert JPG images to PDF.',
        category: 'pdf-tools',
        subCategory: 'Convert to PDF',
        slug: 'jpg-to-pdf',
        icon: '🖼️',
    },
    {
        id: 'word-to-pdf',
        name: 'WORD to PDF',
        description: 'Convert Word documents to PDF.',
        category: 'pdf-tools',
        subCategory: 'Convert to PDF',
        slug: 'word-to-pdf',
        icon: '📝',
    },
    {
        id: 'powerpoint-to-pdf',
        name: 'POWERPOINT to PDF',
        description: 'Convert PowerPoint presentations to PDF.',
        category: 'pdf-tools',
        subCategory: 'Convert to PDF',
        slug: 'powerpoint-to-pdf',
        icon: '📊',
    },
    {
        id: 'excel-to-pdf',
        name: 'EXCEL to PDF',
        description: 'Convert Excel spreadsheets to PDF.',
        category: 'pdf-tools',
        subCategory: 'Convert to PDF',
        slug: 'excel-to-pdf',
        icon: '📈',
    },
    {
        id: 'html-to-pdf',
        name: 'HTML to PDF',
        description: 'Convert webpages to PDF.',
        category: 'pdf-tools',
        subCategory: 'Convert to PDF',
        slug: 'html-to-pdf',
        icon: '🌐',
    },

    // 4. CONVERT FROM PDF
    {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        description: 'Convert PDF pages to JPG images.',
        category: 'pdf-tools',
        subCategory: 'Convert from PDF',
        slug: 'pdf-to-jpg',
        icon: '🖼️',
    },
    {
        id: 'pdf-to-word',
        name: 'PDF to WORD',
        description: 'Convert PDF to editable Word document.',
        category: 'pdf-tools',
        subCategory: 'Convert from PDF',
        slug: 'pdf-to-word',
        icon: '📝',
    },
    {
        id: 'pdf-to-powerpoint',
        name: 'PDF to POWERPOINT',
        description: 'Convert PDF to PowerPoint presentation.',
        category: 'pdf-tools',
        subCategory: 'Convert from PDF',
        slug: 'pdf-to-powerpoint',
        icon: '📊',
    },
    {
        id: 'pdf-to-excel',
        name: 'PDF to EXCEL',
        description: 'Convert PDF to Excel spreadsheet.',
        category: 'pdf-tools',
        subCategory: 'Convert from PDF',
        slug: 'pdf-to-excel',
        icon: '📈',
    },
    {
        id: 'pdf-to-pdf-a',
        name: 'PDF to PDF/A',
        description: 'Convert PDF to PDF/A for archiving.',
        category: 'pdf-tools',
        subCategory: 'Convert from PDF',
        slug: 'pdf-to-pdf-a',
        icon: '🗄️',
    },

    // 5. EDIT PDF
    {
        id: 'rotate-pdf',
        name: 'Rotate PDF',
        description: 'Rotate PDF pages.',
        category: 'pdf-tools',
        subCategory: 'Edit PDF',
        slug: 'rotate-pdf',
        icon: '🔄',
    },
    {
        id: 'add-page-numbers',
        name: 'Add Page Numbers',
        description: 'Add page numbers to PDF.',
        category: 'pdf-tools',
        subCategory: 'Edit PDF',
        slug: 'add-page-numbers',
        icon: '🔢',
    },
    {
        id: 'add-watermark',
        name: 'Add Watermark',
        description: 'Add watermark to PDF pages.',
        category: 'pdf-tools',
        subCategory: 'Edit PDF',
        slug: 'add-watermark',
        icon: '💧',
    },
    {
        id: 'crop-pdf',
        name: 'Crop PDF',
        description: 'Crop PDF pages.',
        category: 'pdf-tools',
        subCategory: 'Edit PDF',
        slug: 'crop-pdf',
        icon: '✂️',
    },
    {
        id: 'edit-pdf',
        name: 'Edit PDF',
        description: 'Edit text and images in PDF.',
        category: 'pdf-tools',
        subCategory: 'Edit PDF',
        slug: 'edit-pdf',
        icon: '✏️',
    },

    // 6. PDF SECURITY
    {
        id: 'unlock-pdf',
        name: 'Unlock PDF',
        description: 'Remove password and restrictions from PDF.',
        category: 'pdf-tools',
        subCategory: 'PDF Security',
        slug: 'unlock-pdf',
        icon: '🔓',
    },
    {
        id: 'protect-pdf',
        name: 'Protect PDF',
        description: 'Encrypt PDF with a password.',
        category: 'pdf-tools',
        subCategory: 'PDF Security',
        slug: 'protect-pdf',
        icon: '🛡️',
    },
    {
        id: 'sign-pdf',
        name: 'Sign PDF',
        description: 'Sign PDF with digital signature.',
        category: 'pdf-tools',
        subCategory: 'PDF Security',
        slug: 'sign-pdf',
        icon: '✒️',
    },
    {
        id: 'redact-pdf',
        name: 'Redact PDF',
        description: 'Permanently remove sensitive information.',
        category: 'pdf-tools',
        subCategory: 'PDF Security',
        slug: 'redact-pdf',
        icon: '⬛',
    },
    {
        id: 'compare-pdf',
        name: 'Compare PDF',
        description: 'Compare two PDF files.',
        category: 'pdf-tools',
        subCategory: 'PDF Security',
        slug: 'compare-pdf',
        icon: '⚖️',
    },

    // --- Calculators: Basic ---
    {
        id: 'simple-calculator',
        name: 'Simple Calculator',
        description: 'Basic calculator for addition, subtraction, multiplication, and division.',
        category: 'calculators',
        subCategory: 'Basic Calculators',
        slug: 'simple-calculator',
        icon: '�',
    },
    {
        id: 'scientific-calculator',
        name: 'Scientific Calculator',
        description: 'Advanced calculator with trigonometric functions.',
        category: 'calculators',
        subCategory: 'Basic Calculators',
        slug: 'scientific-calculator',
        icon: '�',
    },
    {
        id: 'percentage-calculator',
        name: 'Percentage Calculator',
        description: 'Calculate percentages and increases.',
        category: 'calculators',
        subCategory: 'Basic Calculators',
        slug: 'percentage-calculator',
        icon: '％',
    },
    {
        id: 'fraction-calculator',
        name: 'Fraction Calculator',
        description: 'Calculate fractions easily.',
        category: 'calculators',
        subCategory: 'Basic Calculators',
        slug: 'fraction-calculator',
        icon: '½',
    },
    {
        id: 'date-calculator',
        name: 'Date Calculator',
        description: 'Calculate days between two dates.',
        category: 'calculators',
        subCategory: 'Other',
        slug: 'date-calculator',
        icon: '📅',
    },
    {
        id: 'age-calculator',
        name: 'Age Calculator',
        description: 'Calculate your age exactly.',
        category: 'calculators',
        subCategory: 'Other',
        slug: 'age-calculator',
        icon: '🎂',
    },

    // --- Calculators: Finance (Loan & Mortgage) ---
    {
        id: 'mortgage-calculator',
        name: 'Mortgage Calculator',
        description: 'Calculate monthly mortgage payments.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'mortgage-calculator',
        icon: '🏠',
    },
    {
        id: 'auto-loan-calculator',
        name: 'Auto Loan Calculator',
        description: 'Calculate car loan payments.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'auto-loan-calculator',
        icon: '🚗',
    },
    {
        id: 'amortization-calculator',
        name: 'Amortization Calculator',
        description: 'See your loan amortization schedule.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'amortization-calculator',
        icon: '📅',
    },
    {
        id: 'rent-vs-buy-calculator',
        name: 'Rent vs. Buy Calculator',
        description: 'Decide whether to rent or buy a home.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'rent-vs-buy-calculator',
        icon: '🔑',
    },

    // --- Calculators: Finance (Investment) ---
    {
        id: 'roi-calculator',
        name: 'ROI Calculator',
        description: 'Calculate Return on Investment.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'roi-calculator',
        icon: '📈',
    },
    {
        id: 'margin-calculator',
        name: 'Margin Calculator',
        description: 'Calculate gross margin and markup.',
        category: 'calculators',
        subCategory: 'Business', // slightly different subcat
        slug: 'margin-calculator',
        icon: '🏪',
    },
    {
        id: 'inflation-calculator',
        name: 'Inflation Calculator',
        description: 'Calculate value of money over time.',
        category: 'calculators',
        subCategory: 'Economics',
        slug: 'inflation-calculator',
        icon: '💸',
    },
    {
        id: 'salary-calculator',
        name: 'Salary Calculator',
        description: 'Convert annual salary to hourly, monthly.',
        category: 'calculators',
        subCategory: 'Tax & Salary',
        slug: 'salary-calculator',
        icon: '💵',
    },
    {
        id: 'sales-tax-calculator',
        name: 'Sales Tax Calculator',
        description: 'Calculate sales tax and total price.',
        category: 'calculators',
        subCategory: 'Tax & Salary',
        slug: 'sales-tax-calculator',
        icon: '🏷️',
    },

    // --- Existing Finance re-mapped ---
    {
        id: 'emi-calculator',
        name: 'EMI Calculator',
        description: 'Calculate your Equated Monthly Installment.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'emi-calculator',
        icon: '🧮',
    },
    {
        id: 'loan-calculator',
        name: 'Loan Calculator',
        description: 'Calculate loan interest and repayment.',
        category: 'calculators',
        subCategory: 'Loan & Mortgage',
        slug: 'loan-calculator',
        icon: '🏦',
    },
    {
        id: 'fd-calculator',
        name: 'FD Calculator',
        description: 'Calculate Fixed Deposit maturity amount.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'fd-calculator',
        icon: '💰',
    },
    {
        id: 'rd-calculator',
        name: 'RD Calculator',
        description: 'Calculate Recurring Deposit returns.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'rd-calculator',
        icon: '📉',
    },
    {
        id: 'sip-calculator',
        name: 'SIP Calculator',
        description: 'Calculate returns on your Systematic Investment Plan.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'sip-calculator',
        icon: '🌱',
    },
    {
        id: 'gst-calculator',
        name: 'GST Calculator',
        description: 'Calculate GST inclusive and exclusive amounts.',
        category: 'calculators',
        subCategory: 'Tax & Salary',
        slug: 'gst-calculator',
        icon: '📊',
    },
    {
        id: 'income-tax-calculator',
        name: 'Income Tax Calculator',
        description: 'Estimate your income tax liability.',
        category: 'calculators',
        subCategory: 'Tax & Salary',
        slug: 'income-tax-calculator',
        icon: '🧾',
    },
    {
        id: 'currency-converter',
        name: 'Currency Converter',
        description: 'Convert between different currencies.',
        category: 'calculators',
        subCategory: 'Economics',
        slug: 'currency-converter',
        icon: '💱',
    },
    {
        id: 'compound-interest-calculator',
        name: 'Compound Interest',
        description: 'Calculate compound interest on investments.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'compound-interest-calculator',
        icon: '🔄',
    },
    {
        id: 'budget-calculator',
        name: 'Budget Calculator',
        description: 'Plan and manage your monthly budget.',
        category: 'calculators',
        subCategory: 'Personal Finance',
        slug: 'budget-calculator',
        icon: '📒',
    },
    {
        id: 'simple-interest-calculator',
        name: 'Simple Interest',
        description: 'Calculate simple interest.',
        category: 'calculators',
        subCategory: 'Investment',
        slug: 'simple-interest-calculator',
        icon: '➕',
    },
    {
        id: 'retirement-calculator',
        name: 'Retirement Calculator',
        description: 'Plan your retirement savings.',
        category: 'calculators',
        subCategory: 'Retirement',
        slug: 'retirement-calculator',
        icon: '👴',
    },
    {
        id: '401k-calculator',
        name: '401K Calculator',
        description: 'Calculate 401k growth.',
        category: 'calculators',
        subCategory: 'Retirement',
        slug: '401k-calculator',
        icon: '💼',
    },
    {
        id: 'credit-card-payoff-calculator',
        name: 'Credit Card Payoff',
        description: 'Calculate time to pay off credit card debt.',
        category: 'calculators',
        subCategory: 'Debt',
        slug: 'credit-card-payoff-calculator',
        icon: '💳',
    },

    // --- Calculators: Fitness & Health ---
    {
        id: 'bmi-calculator',
        name: 'BMI Calculator',
        description: 'Calculate Body Mass Index.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'bmi-calculator',
        icon: '⚖️',
    },
    {
        id: 'calorie-calculator',
        name: 'Calorie Calculator',
        description: 'Estimate daily calorie needs.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'calorie-calculator',
        icon: '🍎',
    },
    {
        id: 'body-fat-calculator',
        name: 'Body Fat Calculator',
        description: 'Estimate body fat percentage.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'body-fat-calculator',
        icon: '💪',
    },
    {
        id: 'bmr-calculator',
        name: 'BMR Calculator',
        description: 'Calculate Basal Metabolic Rate.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'bmr-calculator',
        icon: '🔥',
    },
    {
        id: 'ideal-weight-calculator',
        name: 'Ideal Weight Calculator',
        description: 'Find your ideal weight range.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'ideal-weight-calculator',
        icon: '🎯',
    },
    {
        id: 'pregnancy-calculator',
        name: 'Pregnancy Calculator',
        description: 'Track pregnancy week by week.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'pregnancy-calculator',
        icon: '🤰',
    },
    {
        id: 'due-date-calculator',
        name: 'Due Date Calculator',
        description: 'Calculate baby due date.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'due-date-calculator',
        icon: '📅',
    },
    {
        id: 'ovulation-calculator',
        name: 'Ovulation Calculator',
        description: 'Estimate most fertile days.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'ovulation-calculator',
        icon: '💐',
    },
    {
        id: 'calories-burned-calculator',
        name: 'Calories Burned',
        description: 'Estimate calories burned by activity.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'calories-burned-calculator',
        icon: '🏃',
    },
    {
        id: 'target-heart-rate-calculator',
        name: 'Target Heart Rate',
        description: 'Find target heart rate zone.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'target-heart-rate-calculator',
        icon: '❤️',
    },

    {
        id: 'macro-calculator',
        name: 'Macro Calculator',
        description: 'Calculate your daily macronutrient needs.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'macro-calculator',
        icon: '🥩',
    },
    {
        id: 'pregnancy-weight-gain-calculator',
        name: 'Pregnancy Weight Gain',
        description: 'Estimate healthy weight gain during pregnancy.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'pregnancy-weight-gain-calculator',
        icon: '⚖️',
    },
    {
        id: 'pregnancy-conception-calculator',
        name: 'Pregnancy Conception',
        description: 'Estimate conception date based on due date.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'pregnancy-conception-calculator',
        icon: '👶',
    },
    {
        id: 'pace-calculator',
        name: 'Pace Calculator',
        description: 'Calculate running pace and speed.',
        category: 'calculators',
        subCategory: 'Fitness & Activity',
        slug: 'pace-calculator',
        icon: '⏱️',
    },
    {
        id: 'army-body-fat-calculator',
        name: 'Army Body Fat',
        description: 'Calculate body fat using Army standards.',
        category: 'calculators',
        subCategory: 'Fitness & Activity',
        slug: 'army-body-fat-calculator',
        icon: '🎖️',
    },
    {
        id: 'carbohydrate-calculator',
        name: 'Carbohydrate Calculator',
        description: 'Estimate daily carbohydrate needs.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'carbohydrate-calculator',
        icon: '🍞',
    },
    {
        id: 'lean-body-mass-calculator',
        name: 'Lean Body Mass',
        description: 'Calculate lean body mass vs fat mass.',
        category: 'calculators',
        subCategory: 'Fitness & Activity',
        slug: 'lean-body-mass-calculator',
        icon: '🏋️',
    },
    {
        id: 'healthy-weight-calculator',
        name: 'Healthy Weight',
        description: 'Find a healthy weight range for your height.',
        category: 'calculators',
        subCategory: 'Weight & BMI',
        slug: 'healthy-weight-calculator',
        icon: '🍏',
    },
    {
        id: 'one-rep-max-calculator',
        name: 'One Rep Max',
        description: 'Estimate your one-repetition max lift.',
        category: 'calculators',
        subCategory: 'Fitness & Activity',
        slug: 'one-rep-max-calculator',
        icon: '🏋️‍♀️',
    },
    {
        id: 'protein-calculator',
        name: 'Protein Calculator',
        description: 'Calculate daily protein requirements.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'protein-calculator',
        icon: '🍗',
    },
    {
        id: 'fat-intake-calculator',
        name: 'Fat Intake Calculator',
        description: 'Calculate daily fat intake needs.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'fat-intake-calculator',
        icon: '🥑',
    },
    {
        id: 'tdee-calculator',
        name: 'TDEE Calculator',
        description: 'Total Daily Energy Expenditure calculator.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'tdee-calculator',
        icon: '⚡',
    },
    {
        id: 'conception-calculator',
        name: 'Conception Calculator',
        description: 'Find best dates for conception.',
        category: 'calculators',
        subCategory: 'Women\'s Health',
        slug: 'conception-calculator',
        icon: '📅',
    },
    {
        id: 'period-calculator',
        name: 'Period Calculator',
        description: 'Track and predict menstrual cycles.',
        category: 'calculators',
        subCategory: 'Women\'s Health',
        slug: 'period-calculator',
        icon: '🩸',
    },
    {
        id: 'gfr-calculator',
        name: 'GFR Calculator',
        description: 'Estimated Glomerular Filtration Rate.',
        category: 'calculators',
        subCategory: 'General Health',
        slug: 'gfr-calculator',
        icon: '🩺',
    },
    {
        id: 'body-type-calculator',
        name: 'Body Type Calculator',
        description: 'Determine your body shape/type.',
        category: 'calculators',
        subCategory: 'General Health',
        slug: 'body-type-calculator',
        icon: '👤',
    },
    {
        id: 'body-surface-area-calculator',
        name: 'Body Surface Area',
        description: 'Calculate total body surface area.',
        category: 'calculators',
        subCategory: 'General Health',
        slug: 'body-surface-area-calculator',
        icon: '📏',
    },
    {
        id: 'bac-calculator',
        name: 'BAC Calculator',
        description: 'Estimate Blood Alcohol Content.',
        category: 'calculators',
        subCategory: 'General Health',
        slug: 'bac-calculator',
        icon: '🍷',
    },
    {
        id: 'anorexic-bmi-calculator',
        name: 'Anorexic BMI',
        description: 'BMI calculator for underweight concerns.',
        category: 'calculators',
        subCategory: 'Weight & BMI',
        slug: 'anorexic-bmi-calculator',
        icon: '⚠️',
    },
    {
        id: 'weight-watchers-points-calculator',
        name: 'Weight Watchers Points',
        description: 'Calculate points for diet plans.',
        category: 'calculators',
        subCategory: 'Diet & Nutrition',
        slug: 'weight-watchers-points-calculator',
        icon: 'points',
    },
    {
        id: 'overweight-calculator',
        name: 'Overweight Calculator',
        description: 'Check overweight status and risks.',
        category: 'calculators',
        subCategory: 'Weight & BMI',
        slug: 'overweight-calculator',
        icon: '⚖️',
    },

    {
        id: 'overweight-calculator',
        name: 'Overweight Calculator',
        description: 'Check overweight status and risks.',
        category: 'calculators',
        subCategory: 'Fitness & Health',
        slug: 'overweight-calculator',
        icon: '⚖️',
    },

    // --- Calculators: Math ---
    {
        id: 'triangle-calculator',
        name: 'Triangle Calculator',
        description: 'Calculate triangle angles and sides.',
        category: 'calculators',
        subCategory: 'Geometry',
        slug: 'triangle-calculator',
        icon: '📐',
    },
    {
        id: 'volume-calculator',
        name: 'Volume Calculator',
        description: 'Calculate volume of various shapes.',
        category: 'calculators',
        subCategory: 'Geometry',
        slug: 'volume-calculator',
        icon: '🧊',
    },
    {
        id: 'standard-deviation-calculator',
        name: 'Standard Deviation',
        description: 'Calculate SD, variance, and mean.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'standard-deviation-calculator',
        icon: '📊',
    },
    {
        id: 'random-number-generator',
        name: 'Random Number Generator',
        description: 'Generate random numbers within a range.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'random-number-generator',
        icon: '🎲',
    },
    {
        id: 'number-sequence-calculator',
        name: 'Number Sequence',
        description: 'Find the next number in a sequence.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'number-sequence-calculator',
        icon: '🔢',
    },
    {
        id: 'percent-error-calculator',
        name: 'Percent Error Calculator',
        description: 'Calculate the percentage error.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'percent-error-calculator',
        icon: '❌',
    },
    {
        id: 'exponent-calculator',
        name: 'Exponent Calculator',
        description: 'Calculate exponents and powers.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'exponent-calculator',
        icon: '📈',
    },
    {
        id: 'binary-calculator',
        name: 'Binary Calculator',
        description: 'Perform binary arithmetic.',
        category: 'calculators',
        subCategory: 'Algebra',
        slug: 'binary-calculator',
        icon: '0️⃣1️⃣',
    },
    {
        id: 'hex-calculator',
        name: 'Hex Calculator',
        description: 'Calculate hexadecimal numbers.',
        category: 'calculators',
        subCategory: 'Algebra',
        slug: 'hex-calculator',
        icon: '🔠',
    },
    {
        id: 'half-life-calculator',
        name: 'Half-Life Calculator',
        description: 'Calculate radioactive half-life.',
        category: 'calculators',
        subCategory: 'Algebra',
        slug: 'half-life-calculator',
        icon: '☢️',
    },
    {
        id: 'quadratic-formula-calculator',
        name: 'Quadratic Formula',
        description: 'Solve quadratic equations.',
        category: 'calculators',
        subCategory: 'Algebra',
        slug: 'quadratic-formula-calculator',
        icon: '✖️',
    },
    {
        id: 'slope-calculator',
        name: 'Slope Calculator',
        description: 'Calculate the slope of a line.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'slope-calculator',
        icon: '📉',
    },
    {
        id: 'log-calculator',
        name: 'Log Calculator',
        description: 'Calculate logarithms.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'log-calculator',
        icon: '🪵',
    },
    {
        id: 'area-calculator',
        name: 'Area Calculator',
        description: 'Calculate area of geometric shapes.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'area-calculator',
        icon: '⬛',
    },
    {
        id: 'sample-size-calculator',
        name: 'Sample Size Calculator',
        description: 'Determine required sample size.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'sample-size-calculator',
        icon: '👥',
    },
    {
        id: 'probability-calculator',
        name: 'Probability Calculator',
        description: 'Calculate probability of events.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'probability-calculator',
        icon: '🎲',
    },
    {
        id: 'statistics-calculator',
        name: 'Statistics Calculator',
        description: 'Calculate basic statistics.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'statistics-calculator',
        icon: '📉',
    },
    {
        id: 'mean-median-mode-calculator',
        name: 'Mean Median Mode',
        description: 'Calculate measures of central tendency.',
        category: 'calculators',
        subCategory: 'Statistics',
        slug: 'mean-median-mode-calculator',
        icon: '📊',
    },
    {
        id: 'permutation-combination-calculator',
        name: 'Permutation &  Combination',
        description: 'Calculate permutations and combinations.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'permutation-combination-calculator',
        icon: '🔄',
    },
    {
        id: 'z-score-calculator',
        name: 'Z-score Calculator',
        description: 'Calculate Z-score from raw score.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'z-score-calculator',
        icon: '🇿',
    },
    {
        id: 'confidence-interval-calculator',
        name: 'Confidence Interval',
        description: 'Calculate confidence intervals.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'confidence-interval-calculator',
        icon: '↔️',
    },
    {
        id: 'ratio-calculator',
        name: 'Ratio Calculator',
        description: 'Solve ratio problems.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'ratio-calculator',
        icon: '➗',
    },
    {
        id: 'distance-calculator',
        name: 'Distance Calculator',
        description: 'Calculate distance between points.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'distance-calculator',
        icon: '📏',
    },
    {
        id: 'circle-calculator',
        name: 'Circle Calculator',
        description: 'Calculate circle properties.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'circle-calculator',
        icon: '⭕',
    },
    {
        id: 'surface-area-calculator',
        name: 'Surface Area Calculator',
        description: 'Calculate surface area of solids.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'surface-area-calculator',
        icon: '📦',
    },
    {
        id: 'pythagorean-theorem-calculator',
        name: 'Pythagorean Theorem',
        description: 'Calculate hypotenuse or sides.',
        category: 'calculators',
        subCategory: 'Numbers',
        slug: 'pythagorean-theorem-calculator',
        icon: '📐',
    },
    {
        id: 'right-triangle-calculator',
        name: 'Right Triangle',
        description: 'Calculate right triangle properties.',
        category: 'calculators',
        subCategory: 'Numbers',
        slug: 'right-triangle-calculator',
        icon: '📐',
    },
    {
        id: 'root-calculator',
        name: 'Root Calculator',
        description: 'Calculate square and cube roots.',
        category: 'calculators',
        subCategory: 'Numbers',
        slug: 'root-calculator',
        icon: '🌳',
    },
    {
        id: 'lcm-calculator',
        name: 'Least Common Multiple',
        description: 'Find LCM of numbers.',
        category: 'calculators',
        subCategory: 'Numbers',
        slug: 'lcm-calculator',
        icon: '🔢',
    },
    {
        id: 'gcf-calculator',
        name: 'Greatest Common Factor',
        description: 'Find GCF of numbers.',
        category: 'calculators',
        subCategory: 'Numbers',
        slug: 'gcf-calculator',
        icon: '🔢',
    },
    {
        id: 'factor-calculator',
        name: 'Factor Calculator',
        description: 'Find factors of a number.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'factor-calculator',
        icon: '✖️',
    },
    {
        id: 'rounding-calculator',
        name: 'Rounding Calculator',
        description: 'Round numbers to decimal places.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'rounding-calculator',
        icon: '🔄',
    },
    {
        id: 'matrix-calculator',
        name: 'Matrix Calculator',
        description: 'Perform matrix operations.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'matrix-calculator',
        icon: '▦',
    },
    {
        id: 'scientific-notation-calculator',
        name: 'Scientific Notation',
        description: 'Convert to scientific notation.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'scientific-notation-calculator',
        icon: '🔬',
    },
    {
        id: 'big-number-calculator',
        name: 'Big Number Calculator',
        description: 'Calculate with very large numbers.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'big-number-calculator',
        icon: '🐘',
    },
    {
        id: 'prime-factorization-calculator',
        name: 'Prime Factorization',
        description: 'Find prime factors of a number.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'prime-factorization-calculator',
        icon: '🔢',
    },
    {
        id: 'common-factor-calculator',
        name: 'Common Factor',
        description: 'Find common factors.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'common-factor-calculator',
        icon: '🤝',
    },
    {
        id: 'long-division-calculator',
        name: 'Long Division Calculator',
        description: 'Perform long division with steps.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'long-division-calculator',
        icon: '➗',
    },
    {
        id: 'average-calculator',
        name: 'Average Calculator',
        description: 'Calculate the average of numbers.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'average-calculator',
        icon: '📊',
    },
    {
        id: 'p-value-calculator',
        name: 'P-value Calculator',
        description: 'Calculate P-value from Z, T, F scores.',
        category: 'calculators',
        subCategory: 'Math',
        slug: 'p-value-calculator',
        icon: '🅿️',
    },

    // --- Calculators: Other ---
    {
        id: 'time-calculator',
        name: 'Time Calculator',
        description: 'Add or subtract time values.',
        category: 'calculators',
        subCategory: 'Other',
        slug: 'time-calculator',
        icon: '⌚',
    },
    {
        id: 'hours-calculator',
        name: 'Hours Calculator',
        description: 'Calculate hours worked.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'hours-calculator',
        icon: '⏳',
    },
    {
        id: 'gpa-calculator',
        name: 'GPA Calculator',
        description: 'Calculate Grade Point Average.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'gpa-calculator',
        icon: '🎓',
    },
    {
        id: 'grade-calculator',
        name: 'Grade Calculator',
        description: 'Calculate final grade needed.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'grade-calculator',
        icon: '📝',
    },
    {
        id: 'height-calculator',
        name: 'Height Calculator',
        description: 'Predict child\'s future height.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'height-calculator',
        icon: '📏',
    },
    {
        id: 'concrete-calculator',
        name: 'Concrete Calculator',
        description: 'Estimate concrete needed for a project.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'concrete-calculator',
        icon: '🧱',
    },
    {
        id: 'ip-subnet-calculator',
        name: 'IP Subnet Calculator',
        description: 'Calculate IP subnets.',
        category: 'calculators',
        subCategory: 'Technology',
        slug: 'ip-subnet-calculator',
        icon: '🌐',
    },
    {
        id: 'bra-size-calculator',
        name: 'Bra Size Calculator',
        description: 'Find your correct bra size.',
        category: 'calculators',
        subCategory: 'Technology',
        slug: 'bra-size-calculator',
        icon: '👙',
    },
    {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Generate secure passwords.',
        category: 'calculators',
        subCategory: 'Technology',
        slug: 'password-generator',
        icon: '🔒',
    },
    {
        id: 'dice-roller',
        name: 'Dice Roller',
        description: 'Roll virtual dice.',
        category: 'calculators',
        subCategory: 'Technology',
        slug: 'dice-roller',
        icon: '🎲',
    },
    {
        id: 'conversion-calculator',
        name: 'Conversion Calculator',
        description: 'Convert between various units.',
        category: 'calculators',
        subCategory: 'Technology',
        slug: 'conversion-calculator',
        icon: '🔄',
    },
    {
        id: 'fuel-cost-calculator',
        name: 'Fuel Cost Calculator',
        description: 'Calculate trip fuel costs.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'fuel-cost-calculator',
        icon: '⛽',
    },
    {
        id: 'voltage-drop-calculator',
        name: 'Voltage Drop Calculator',
        description: 'Calculate voltage drop in wires.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'voltage-drop-calculator',
        icon: '⚡',
    },
    {
        id: 'btu-calculator',
        name: 'BTU Calculator',
        description: 'Calculate AC BTU needs.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'btu-calculator',
        icon: '❄️',
    },
    {
        id: 'square-footage-calculator',
        name: 'Square Footage',
        description: 'Calculate area in square feet.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'square-footage-calculator',
        icon: '⬛',
    },
    {
        id: 'time-card-calculator',
        name: 'Time Card Calculator',
        description: 'Calculate weekly work hours.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'time-card-calculator',
        icon: '📋',
    },
    {
        id: 'time-zone-calculator',
        name: 'Time Zone Calculator',
        description: 'Convert time between zones.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'time-zone-calculator',
        icon: '🌍',
    },
    {
        id: 'love-calculator',
        name: 'Love Calculator',
        description: 'Calculate love compatibility.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'love-calculator',
        icon: '💘',
    },
    {
        id: 'gdp-calculator',
        name: 'GDP Calculator',
        description: 'Calculate Gross Domestic Product.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'gdp-calculator',
        icon: '📈',
    },
    {
        id: 'gas-mileage-calculator',
        name: 'Gas Mileage Calculator',
        description: 'Calculate MPG/KPL.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'gas-mileage-calculator',
        icon: '🚗',
    },
    {
        id: 'horsepower-calculator',
        name: 'Horsepower Calculator',
        description: 'Calculate HP from torque/RPM.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'horsepower-calculator',
        icon: '🐎',
    },
    {
        id: 'engine-horsepower-calculator',
        name: 'Engine HP Calculator',
        description: 'Estimate engine horsepower.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'engine-horsepower-calculator',
        icon: '⚙️',
    },
    {
        id: 'stair-calculator',
        name: 'Stair Calculator',
        description: 'Calculate stair dimensions.',
        category: 'calculators',
        subCategory: 'Construction',
        slug: 'stair-calculator',
        icon: '🪜',
    },
    {
        id: 'resistor-calculator',
        name: 'Resistor Calculator',
        description: 'Identify resistor values.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'resistor-calculator',
        icon: '🔌',
    },
    {
        id: 'ohms-law-calculator',
        name: 'Ohms Law Calculator',
        description: 'Calculate V, I, R, P.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'ohms-law-calculator',
        icon: '🔋',
    },
    {
        id: 'electricity-calculator',
        name: 'Electricity Calculator',
        description: 'Calculate electricity costs.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'electricity-calculator',
        icon: '💡',
    },
    {
        id: 'shoe-size-conversion',
        name: 'Shoe Size Conversion',
        description: 'Convert shoe sizes.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'shoe-size-conversion',
        icon: '👟',
    },
    {
        id: 'tip-calculator',
        name: 'Tip Calculator',
        description: 'Calculate gratuity and split bill.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'tip-calculator',
        icon: '💵',
    },
    {
        id: 'mileage-calculator',
        name: 'Mileage Calculator',
        description: 'Calculate vehicle mileage.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'mileage-calculator',
        icon: '🛣️',
    },
    {
        id: 'density-calculator',
        name: 'Density Calculator',
        description: 'Calculate mass, volume, density.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'density-calculator',
        icon: '🧱',
    },
    {
        id: 'mass-calculator',
        name: 'Mass Calculator',
        description: 'Calculate object mass.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'mass-calculator',
        icon: '⚖️',
    },
    {
        id: 'weight-calculator',
        name: 'Weight Calculator',
        description: 'Convert weight units.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'weight-calculator',
        icon: '🏋️',
    },
    {
        id: 'speed-calculator',
        name: 'Speed Calculator',
        description: 'Calculate speed, distance, time.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'speed-calculator',
        icon: '🏎️',
    },
    {
        id: 'molarity-calculator',
        name: 'Molarity Calculator',
        description: 'Calculate solution concentration.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'molarity-calculator',
        icon: '🧪',
    },
    {
        id: 'molecular-weight-calculator',
        name: 'Molecular Weight',
        description: 'Calculate molecule weight.',
        category: 'calculators',
        subCategory: 'Science & Engineering',
        slug: 'molecular-weight-calculator',
        icon: '⚛️',
    },
    {
        id: 'roman-numeral-converter',
        name: 'Roman Numeral Converter',
        description: 'Convert to/from Roman numerals.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'roman-numeral-converter',
        icon: '🏛️',
    },
    {
        id: 'golf-handicap-calculator',
        name: 'Golf Handicap',
        description: 'Calculate golf handicap index.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'golf-handicap-calculator',
        icon: '⛳',
    },
    {
        id: 'sleep-calculator',
        name: 'Sleep Calculator',
        description: 'Calculate wake up times.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'sleep-calculator',
        icon: '😴',
    },
    {
        id: 'tire-size-calculator',
        name: 'Tire Size Calculator',
        description: 'Compare tire dimensions.',
        category: 'calculators',
        subCategory: 'Everyday Life',
        slug: 'tire-size-calculator',
        icon: '🛞',
    },
    {
        id: 'roofing-calculator',
        name: 'Roofing Calculator',
        description: 'Estimate roofing materials.',
        category: 'calculators',
        subCategory: 'Construction',
        slug: 'roofing-calculator',
        icon: '🏠',
    },
    {
        id: 'tile-calculator',
        name: 'Tile Calculator',
        description: 'Estimate tiles needed.',
        category: 'calculators',
        subCategory: 'Construction',
        slug: 'tile-calculator',
        icon: '⬜',
    },
    {
        id: 'mulch-calculator',
        name: 'Mulch Calculator',
        description: 'Estimate mulch amount.',
        category: 'calculators',
        subCategory: 'Construction',
        slug: 'mulch-calculator',
        icon: '🍂',
    },
    {
        id: 'gravel-calculator',
        name: 'Gravel Calculator',
        description: 'Estimate gravel tonnage.',
        category: 'calculators',
        subCategory: 'Construction',
        slug: 'gravel-calculator',
        icon: '🪨',
    },
    {
        id: 'wind-chill-calculator',
        name: 'Wind Chill Calculator',
        description: 'Calculate wind chill factor.',
        category: 'calculators',
        subCategory: 'Weather',
        slug: 'wind-chill-calculator',
        icon: '🌬️',
    },
    {
        id: 'heat-index-calculator',
        name: 'Heat Index Calculator',
        description: 'Calculate heat index.',
        category: 'calculators',
        subCategory: 'Weather',
        slug: 'heat-index-calculator',
        icon: '🌡️',
    },
    {
        id: 'dew-point-calculator',
        name: 'Dew Point Calculator',
        description: 'Calculate dew point temperature.',
        category: 'calculators',
        subCategory: 'Weather',
        slug: 'dew-point-calculator',
        icon: '💧',
    },
    {
        id: 'bandwidth-calculator',
        name: 'Bandwidth Calculator',
        description: 'Calculate data transfer time.',
        category: 'calculators',
        subCategory: 'Weather',
        slug: 'bandwidth-calculator',
        icon: '📶',
    },
    {
        id: 'time-duration-calculator',
        name: 'Time Duration',
        description: 'Calculate duration between times.',
        category: 'calculators',
        subCategory: 'Time & Date',
        slug: 'time-duration-calculator',
        icon: '⏱️',
    },
    {
        id: 'day-counter',
        name: 'Day Counter',
        description: 'Count days between dates.',
        category: 'calculators',
        subCategory: 'Time & Date',
        slug: 'day-counter',
        icon: '📆',
    },
    {
        id: 'day-of-the-week-calculator',
        name: 'Day of the Week',
        description: 'Find the day of the week.',
        category: 'calculators',
        subCategory: 'Time & Date',
        slug: 'day-of-the-week-calculator',
        icon: '📅',
    },

    // --- Calculators: Widgets ---
    {
        id: 'mortgage-calculator-widget',
        name: 'Mortgage Calculator for Your Site',
        description: 'Embeddable mortgage calculator widget.',
        category: 'calculators',
        subCategory: 'Calculators for Your Site',
        slug: 'mortgage-calculator-widget',
        icon: '🏠',
    },
    {
        id: 'math-calculator-widget',
        name: 'Math Calculator for Your Site',
        description: 'Embeddable math calculator widget.',
        category: 'calculators',
        subCategory: 'Calculators for Your Site',
        slug: 'math-calculator-widget',
        icon: '🧮',
    },
    {
        id: 'scientific-calculator-widget',
        name: 'Scientific Calculator for Your Site',
        description: 'Embeddable scientific calculator widget.',
        category: 'calculators',
        subCategory: 'Calculators for Your Site',
        slug: 'scientific-calculator-widget',
        icon: '🔬',
    },
    {
        id: 'love-calculator-widget',
        name: 'Love Calculator for Your Site',
        description: 'Embeddable love calculator widget.',
        category: 'calculators',
        subCategory: 'Calculators for Your Site',
        slug: 'love-calculator-widget',
        icon: '💘',
    },
    {
        id: 'concrete-calculator-widget',
        name: 'Concrete Calculator for Your Site',
        description: 'Embeddable concrete calculator widget.',
        category: 'calculators',
        subCategory: 'Calculators for Your Site',
        slug: 'concrete-calculator-widget',
        icon: '🧱',
    },

    // --- Image Tools ---
    // 1. Basic Conversions
    {
        id: 'jpg-to-png',
        name: 'JPG to PNG',
        description: 'Convert JPG images to PNG format.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'jpg-to-png',
        icon: '🖼️',
    },
    {
        id: 'png-to-jpg',
        name: 'PNG to JPG',
        description: 'Convert PNG images to JPG format.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'png-to-jpg',
        icon: '🔄',
    },
    {
        id: 'webp-to-jpg',
        name: 'WebP to JPG',
        description: 'Convert WebP images to JPG format.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'webp-to-jpg',
        icon: '📄',
    },
    {
        id: 'jpg-to-webp',
        name: 'JPG to WebP',
        description: 'Convert JPG images to WebP format.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'jpg-to-webp',
        icon: '🌐',
    },
    {
        id: 'heic-to-jpg',
        name: 'HEIC to JPG',
        description: 'Convert iPhone HEIC images to JPG.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'heic-to-jpg',
        icon: '📱',
    },
    {
        id: 'image-to-base64',
        name: 'Image to Base64',
        description: 'Convert image to Base64 string.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'image-to-base64',
        icon: '💻',
    },
    {
        id: 'base64-to-image',
        name: 'Base64 to Image',
        description: 'Convert Base64 string to image.',
        category: 'image-tools',
        subCategory: 'Basic Conversions',
        slug: 'base64-to-image',
        icon: '🖼️',
    },

    // 2. Resize/Crop/Rotate
    {
        id: 'image-resizer',
        name: 'Image Resize',
        description: 'Resize images to specific dimensions.',
        category: 'image-tools',
        subCategory: 'Editing',
        slug: 'image-resizer',
        icon: '📐',
    },
    {
        id: 'image-crop',
        name: 'Image Crop',
        description: 'Crop specific areas of an image.',
        category: 'image-tools',
        subCategory: 'Editing',
        slug: 'image-crop',
        icon: '✂️',
    },
    {
        id: 'image-rotate',
        name: 'Image Rotate',
        description: 'Rotate images by 90, 180, or 270 degrees.',
        category: 'image-tools',
        subCategory: 'Editing',
        slug: 'image-rotate',
        icon: '🔄',
    },
    {
        id: 'image-flip',
        name: 'Image Flip',
        description: 'Flip images horizontally or vertically.',
        category: 'image-tools',
        subCategory: 'Editing',
        slug: 'image-flip',
        icon: '↔️',
    },

    // 3. Compression/Quality
    {
        id: 'image-compressor',
        name: 'Image Compress',
        description: 'Compress images to reduce file size.',
        category: 'image-tools',
        subCategory: 'Optimization',
        slug: 'image-compressor',
        icon: '📉',
    },
    {
        id: 'image-quality',
        name: 'Change Quality',
        description: 'Adjust image quality slider.',
        category: 'image-tools',
        subCategory: 'Optimization',
        slug: 'image-quality',
        icon: '🎚️',
    },
    {
        id: 'image-dpi',
        name: 'Change DPI',
        description: 'Adjust image DPI resolution.',
        category: 'image-tools',
        subCategory: 'Optimization',
        slug: 'image-dpi',
        icon: '🖨️',
    },

    // 4. Color & Filter Tools
    {
        id: 'brightness-adjust',
        name: 'Brightness Adjust',
        description: 'Change image brightness levels.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'brightness-adjust',
        icon: '☀️',
    },
    {
        id: 'contrast-adjust',
        name: 'Contrast Adjust',
        description: 'Adjust image contrast.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'contrast-adjust',
        icon: '🌗',
    },
    {
        id: 'saturation-adjust',
        name: 'Saturation Adjust',
        description: 'Change image color saturation.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'saturation-adjust',
        icon: '🎨',
    },
    {
        id: 'temp-adjust',
        name: 'Temperature',
        description: 'Adjust image warmth and coolness.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'temp-adjust',
        icon: '🌡️',
    },
    {
        id: 'filter-bw',
        name: 'Black & White',
        description: 'Convert image to black and white.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-bw',
        icon: '⚫',
    },
    {
        id: 'filter-sepia',
        name: 'Sepia Filter',
        description: 'Apply vintage sepia tone.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-sepia',
        icon: '🟤',
    },
    {
        id: 'filter-negative',
        name: 'Negative Filter',
        description: 'Invert image colors.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-negative',
        icon: '🎭',
    },
    {
        id: 'filter-blur',
        name: 'Blur Image',
        description: 'Apply Gaussian blur to image.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-blur',
        icon: '🌫️',
    },
    {
        id: 'filter-sharpen',
        name: 'Sharpen Image',
        description: 'Enhance image details.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-sharpen',
        icon: '🗡️',
    },
    {
        id: 'filter-vignette',
        name: 'Vignette Effect',
        description: 'Add vignette borders.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-vignette',
        icon: '🌑',
    },
    {
        id: 'filter-pixelate',
        name: 'Pixelate Image',
        description: 'Pixelate image privacy effect.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-pixelate',
        icon: '👾',
    },
    {
        id: 'filter-posterize',
        name: 'Posterize',
        description: 'Reduce number of colors.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-posterize',
        icon: '🎨',
    },
    {
        id: 'filter-vintage',
        name: 'Vintage Effect',
        description: 'Apply retro photo look.',
        category: 'image-tools',
        subCategory: 'Filters',
        slug: 'filter-vintage',
        icon: '📸',
    },

    // 5. Text & Drawing
    {
        id: 'add-text-image',
        name: 'Add Text to Image',
        description: 'Overlay text on images.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'add-text-image',
        icon: '🔤',
    },
    {
        id: 'watermark-text',
        name: 'Add Watermark (Text)',
        description: 'Stamp text watermark.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'watermark-text',
        icon: '©️',
    },
    {
        id: 'watermark-image',
        name: 'Add Watermark (Image)',
        description: 'Overlay logo watermark.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'watermark-image',
        icon: '🖼️',
    },
    {
        id: 'draw-on-image',
        name: 'Draw on Image',
        description: 'Freehand drawing brush.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'draw-on-image',
        icon: '🖌️',
    },
    {
        id: 'add-shapes',
        name: 'Add Shapes',
        description: 'Add rectangles, circles, arrows.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'add-shapes',
        icon: '⭕',
    },
    {
        id: 'add-sticker',
        name: 'Add Stickers',
        description: 'Add fun stickers to photos.',
        category: 'image-tools',
        subCategory: 'Drawing',
        slug: 'add-sticker',
        icon: '😊',
    },

    // 6. Utility Tools
    {
        id: 'color-picker',
        name: 'Color Picker',
        description: 'Pick HEX/RGB color from image.',
        category: 'image-tools',
        subCategory: 'Utilities',
        slug: 'color-picker',
        icon: '🎨',
    },
    {
        id: 'get-metadata',
        name: 'Get EXIF Data',
        description: 'View image EXIF metadata.',
        category: 'image-tools',
        subCategory: 'Utilities',
        slug: 'get-metadata',
        icon: 'ℹ️',
    },
    {
        id: 'remove-metadata',
        name: 'Remove EXIF',
        description: 'Strip sensitive metadata.',
        category: 'image-tools',
        subCategory: 'Utilities',
        slug: 'remove-metadata',
        icon: '🗑️',
    },
    {
        id: 'image-redactor',
        name: 'Image Redactor',
        description: 'Blackout sensitive areas.',
        category: 'image-tools',
        subCategory: 'Utilities',
        slug: 'image-redactor',
        icon: '⬛',
    },
    {
        id: 'thumbnail-maker',
        name: 'Thumbnail Maker',
        description: 'Create YouTube thumbnails.',
        category: 'image-tools',
        subCategory: 'Utilities',
        slug: 'thumbnail-maker',
        icon: '🖼️',
    },
    // --- AI / ML Powered Tools ---
    {
        id: 'bg-remove',
        name: 'Background Remover',
        description: 'Remove image background automatically using AI.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'bg-remove',
        icon: '🎭',
    },
    {
        id: 'face-blur',
        name: 'Face Blur',
        description: 'Automatically blur faces in photos for privacy.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'face-blur',
        icon: '😶',
    },
    {
        id: 'object-remover',
        name: 'Magic Eraser',
        description: 'Remove unwanted objects or people from photos.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'object-remover',
        icon: '🧼',
    },
    {
        id: 'ai-upscaler',
        name: 'AI Image Upscaler',
        description: 'Upscale images 2x or 4x without losing quality.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'ai-upscaler',
        icon: '🔍',
    },
    {
        id: 'photo-enhancer',
        name: 'Photo Enhancer',
        description: 'Improve clarity and resolution of old photos.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'photo-enhancer',
        icon: '✨',
    },
    {
        id: 'skin-smoothing',
        name: 'Face Cleanup',
        description: 'Smooth skin and remove blemishes from portraits.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'skin-smoothing',
        icon: '🧖',
    },
    {
        id: 'colorize-photo',
        name: 'Colorize Photo',
        description: 'Turn black and white photos into color with AI.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'colorize-photo',
        icon: '🌈',
    },
    {
        id: 'noise-reduction',
        name: 'Denoise Image',
        description: 'Remove grain and noise from low-light photos.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'noise-reduction',
        icon: '🔇',
    },
    {
        id: 'ai-deblur',
        name: 'Unblur Image',
        description: 'Sharpen out-of-focus or motion-blurred images.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'ai-deblur',
        icon: '👓',
    },
    {
        id: 'text-remover',
        name: 'Remove Text',
        description: 'Cleanly remove text overlays from images.',
        category: 'image-tools',
        subCategory: 'AI / ML Powered',
        slug: 'text-remover',
        icon: '📝',
    },

    // --- Heavy File Processing ---
    {
        id: 'raw-to-jpg',
        name: 'RAW to JPG',
        description: 'Convert professional RAW camera files to JPG.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'raw-to-jpg',
        icon: '📷',
    },
    {
        id: 'psd-to-jpg',
        name: 'PSD to JPG',
        description: 'Convert Photoshop files to JPG without Photoshop.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'psd-to-jpg',
        icon: '🔷',
    },
    {
        id: 'eps-to-png',
        name: 'EPS/SVG to PNG',
        description: 'Convert vector graphics to high-res PNG.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'eps-to-png',
        icon: '📐',
    },
    {
        id: 'image-to-pdf',
        name: 'Image to PDF',
        description: 'Combine multiple images into a single PDF.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'image-to-pdf',
        icon: '📄',
    },
    {
        id: 'gif-maker',
        name: 'GIF Maker',
        description: 'Create animated GIFs from a series of images.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'gif-maker',
        icon: '🎞️',
    },
    {
        id: 'gif-compressor',
        name: 'Compress GIF',
        description: 'Reduce GIF file size for faster sharing.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'gif-compressor',
        icon: '📉',
    },
    {
        id: 'webp-maker',
        name: 'Animated WebP',
        description: 'Create modern animated WebP files.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'webp-maker',
        icon: '🌐',
    },
    {
        id: 'exif-fixer',
        name: 'Fix Orientation',
        description: 'Permanently fix rotated EXIF orientation.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'exif-fixer',
        icon: '🔄',
    },
    {
        id: 'gif-bg-remove',
        name: 'GIF Background Remove',
        description: 'Remove background from animated GIFs.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: 'gif-bg-remove',
        icon: '👻',
    },
    {
        id: '3d-image-maker',
        name: '3D Photo Maker',
        description: 'Generate 3D depth effect from 2D images.',
        category: 'image-tools',
        subCategory: 'Heavy Processing',
        slug: '3d-image-maker',
        icon: '🕶️',
    },
];

export const categories = [
    { id: 'pdf-tools', name: 'PDF Tools', icon: '📄' },
    { id: 'calculators', name: 'Calculators', icon: '🧮' },
    { id: 'image-tools', name: 'Image Tools', icon: '🖼️' },
];
